// Regenerate src/generated/api.ts from the API's OpenAPI document.
// OPENAPI_URL defaults to production; point it at http://localhost:3000/v1/openapi.json to build
// against an unreleased API.
import { writeFile } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';

const url = process.env.OPENAPI_URL ?? 'https://api.lucklogic.dev/v1/openapi.json';
const res = await fetch(url);
if (!res.ok) throw new Error(`${url} answered ${res.status}`);
// defaultNonNullable: false keeps fields that have a server-side default optional in request bodies.
const ast = await openapiTS(await res.json(), { alphabetize: true, defaultNonNullable: false });
const header = `// Generated by scripts/generate.mjs from ${url}. Do not edit by hand.\n\n`;
await writeFile(new URL('../src/generated/api.ts', import.meta.url), header + astToString(ast));
console.log(`src/generated/api.ts written from ${url}`);
